In [28]:
import tensorflow.python.keras as k
from tensorflow.python.keras.datasets import mnist
from tensorflow.python.keras.utils.np_utils import to_categorical
from tensorflow import random
import numpy as np

random.set_seed(1024)
k.backend.set_floatx("posit160")
k.backend.floatx()

'posit160'

In [42]:
random.set_seed(0)
layer = k.layers.Dropout(.2, input_shape=(2,))
data = np.arange(10).reshape(5, 2).astype("posit160")
data

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=posit160)

In [37]:
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]], shape=(5, 2), dtype=posit160)


In [39]:
import tensorflow as tf

In [43]:
tf.identity(data)

<tf.Tensor: shape=(5, 2), dtype=posit160, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=posit160)>